# Generated by Django 3.2 on 2021-11-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('quality', models.CharField(blank=True, max_length=10, null=True)),
                ('pitch', models.CharField(blank=True, max_length=10, null=True)),
                ('recording', models.FileField(upload_to='recordings/')),
            ],
        ),
    ]
