# Generated by Django 3.2 on 2021-05-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_audio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
